---
title: "Week 4 Homework"
output: html_document
date: "2022-10-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prepping Data for Plotting

Calling the required libraries 

```{r cars}
library(dplyr)
library(here)
library(sf)
library(tmap)
library(countrycode)
library(janitor)
```

Read in the data, select the required columns and create a new column with the hdi difference

``` {r}
data <- read.csv(here::here(('HDR21-22_Composite_indices_complete_time_series.csv'))) %>%
  clean_names() %>%
  dplyr::select(starts_with("hdi_2010"), starts_with("hdi_2019"), starts_with("ISO")) %>%
  mutate(hdi_diff = hdi_2019 - hdi_2010)
```

Call in the required shapefiles

```{r}
shapefile <- st_read(here::here('World_Countries_(Generalized)','World_Countries__Generalized_.shp'))
```

Converts the ISO in the shapefile from ISO 2 character to ISO 3 character, which is the version in the dataset
```{r}
shapefile$ISO <- countrycode(shapefile$ISO, origin = 'iso2c', destination = 'iso3c')
```

Merge together the csv with the shapefile, ready for plotting
```{r}
plottingdf <- shapefile %>%
    merge(., 
        data,
        by.x = 'ISO',
        by.y = 'iso3')
```

